name: Eggplant Runner Build

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  Run-Test-Configuration:
    strategy:
      max-parallel: 1
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    name: Run Test Configuration
    steps:
      - run: echo "Trigger event.. ${{ github.event_name }}. Runner OS.. ${{ runner.os }}."
      - name: Eggplant Runner
        uses: TestPlant/eggplant-github-action@main
        with:
          dryRun: false
          serverURL: "https://edge.dai.webperfdev.com/"
          clientID: "client:dai:agent:integration"
          testConfigID: "307fee3e-9d6b-43e6-b31e-f1d379f27cdf" # Test configuration which need to perform execution
          clientSecret: "c38ce33d-5644-4198-b28f-9cf3d9ac05e4" # Eggplant DAI service client secret
            
          # Alternatively, DAI client secret can be set as repo secret
          # by going to GitHub Settings > Secrets > Actions
          # clientSecret: "${{secrets.DAI_CLIENT_SECRET}}"
